name: Docker Hub Push and Vulnerability Scan
on:
  push:
# Publish server tags as releases.
    tags: [ '*' ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          pull: true
          cache-from: type=registry,ref=sondngyn/wgrib2:latest
          cache-to: type=inline
          tags: sondngyn/wgrib2:latest
      -
       name: Snyk scan for vulnerabilities
       uses: snyk/actions/docker@master
       env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
       with:
         image: sondngyn/wgrib2
#        only report high severity
         args: --severity-threshold=high
